version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
